extends: default
rules:
  # Keep defaults but ignore long lines in generated files
  line-length: disable

ignore: |
  # Ignore dockerignore and other dotfiles that are not YAML
  **/.dockerignore
  **/.env
  **/*.env
  **/.gitignore
  **/.gitattributes
  **/LICENSE
  **/*.md
