-- Flyway baseline for user-service
CREATE TABLE IF NOT EXISTS USERS (
  ID BIGSERIAL PRIMARY KEY,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ROLES (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);
