-- user-service schema (Oracle 12c+ for Testcontainers)
-- Creates full schema for integration tests since production uses pre-existing baseline

-- Core users and RBAC -------------------------------------------------------
CREATE TABLE USERS (
  ID              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL           VARCHAR2(320) NOT NULL,
  PASSWORD_HASH   VARCHAR2(255) NOT NULL,
  FULL_NAME       VARCHAR2(200),
  IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
  CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  LAST_LOGIN_AT   TIMESTAMP(6),
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE ROLES (
  ID    NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME  VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE USER_ROLES (
  USER_ID  NUMBER(19) NOT NULL,
  ROLE_ID  NUMBER(19) NOT NULL,
  CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

-- Auth tokens ---------------------------------------------------------------
CREATE TABLE REFRESH_TOKENS (
  ID          NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID     NUMBER(19) NOT NULL,
  TOKEN_HASH  VARCHAR2(255) NOT NULL UNIQUE,
  EXPIRES_AT  TIMESTAMP(6) NOT NULL,
  CREATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  REVOKED_AT  TIMESTAMP(6),
  CONSTRAINT FK_RT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE EMAIL_VERIFICATION_TOKENS (
  ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID      NUMBER(19) NOT NULL,
  TOKEN_HASH   VARCHAR2(255) NOT NULL UNIQUE,
  EXPIRES_AT   TIMESTAMP(6) NOT NULL,
  USED_AT      TIMESTAMP(6),
  CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_EVT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE PASSWORD_RESET_TOKENS (
  ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID      NUMBER(19) NOT NULL,
  TOKEN_HASH   VARCHAR2(255) NOT NULL UNIQUE,
  EXPIRES_AT   TIMESTAMP(6) NOT NULL,
  USED_AT      TIMESTAMP(6),
  CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_PRT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Login audit ---------------------------------------------------------------
CREATE TABLE LOGIN_AUDIT (
  ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID      NUMBER(19),
  EMAIL        VARCHAR2(320),
  SUCCESS      NUMBER(1) DEFAULT 0 NOT NULL CHECK (SUCCESS IN (0,1)),
  REMOTE_IP    VARCHAR2(64),
  USER_AGENT   VARCHAR2(255),
  CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_LOGIN_AUDIT_USER_ID ON LOGIN_AUDIT(USER_ID);
CREATE INDEX IX_LOGIN_AUDIT_CREATED_AT ON LOGIN_AUDIT(CREATED_AT);

-- Optional outbox for domain events ----------------------------------------
CREATE TABLE DOMAIN_EVENTS (
  ID           NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AGGREGATE_ID VARCHAR2(64) NOT NULL,
  TYPE         VARCHAR2(100) NOT NULL,
  PAYLOAD      CLOB,
  CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PUBLISHED_AT TIMESTAMP(6)
);

-- Seed baseline roles -------------------------------------------------------
INSERT INTO ROLES (NAME) VALUES ('customer');
INSERT INTO ROLES (NAME) VALUES ('admin');
INSERT INTO ROLES (NAME) VALUES ('USER');
INSERT INTO ROLES (NAME) VALUES ('ADMIN');
