-- Flyway baseline for order-service
CREATE TABLE IF NOT EXISTS ORDERS (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  STATUS VARCHAR(50) NOT NULL,
  TOTAL NUMERIC(12,2) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) -- assumes USERS table exists from user-service migrations
);

CREATE TABLE IF NOT EXISTS CARTS (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
