{{- range .Values.targets }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .bindingName | default "deployer-binding" }}
  namespace: {{ .namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .serviceAccount | default "arc-runner-sa" }}
    namespace: {{ .subjectNamespace | default "arc-runners" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .roleName | default "deployer" }}
---
{{- end }}
