{{- if .Values.autoscaling.enabled }}
{{- /* Frontend HPA */}}
{{- if .Values.frontend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "umbrella.fullname" . }}-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "umbrella.fullname" . }}-frontend
  minReplicas: {{ .Values.autoscaling.frontend.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.frontend.maxReplicas | default 3 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.frontend.targetCPUUtilizationPercentage | default 70 }}
{{- end }}

---
{{- /* Product Service HPA */}}
{{- if .Values.product.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "umbrella.fullname" . }}-product
  minReplicas: {{ .Values.autoscaling.product.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.product.maxReplicas | default 3 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.product.targetCPUUtilizationPercentage | default 70 }}
{{- end }}

---
{{- /* User Service HPA */}}
{{- if .Values.user.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: {{ .Values.autoscaling.user.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.user.maxReplicas | default 3 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.user.targetCPUUtilizationPercentage | default 70 }}
{{- end }}

---
{{- /* Order Service HPA */}}
{{- if .Values.order.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: {{ .Values.autoscaling.order.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.order.maxReplicas | default 3 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.order.targetCPUUtilizationPercentage | default 70 }}
{{- end }}

---
{{- /* Notification Service HPA */}}
{{- if .Values.notification.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: {{ .Values.autoscaling.notification.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.notification.maxReplicas | default 2 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.notification.targetCPUUtilizationPercentage | default 70 }}
{{- end }}
{{- end }}