-- Migration: create ORDERS table used by order-service tests
CREATE TABLE IF NOT EXISTS ORDERS (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  STATUS VARCHAR(50) NOT NULL,
  TOTAL NUMERIC(12,2) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Index on user for quick lookups
CREATE INDEX IF NOT EXISTS ORDERS_USER_ID_IDX ON ORDERS (USER_ID);
